feedback/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.feedback_index, name='feedback-main'), 
    path('done/', views.done, name='feedback-done'), 
    path('<int:id_feedback>/', views.update_feedback, name='feedback-done'), 

]

movie/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = "Русская админка"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie_app.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

movie_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.show_all_movie, name='main'),
    path('movie/<str:slug_movie>', views.show_one_movie, name="movie-detail"),
    path('directors', views.show_all_directors, name='directors-main'),
    path('directors/<int:id_director>', views.show_one_director, name="director-detail"),
    path('actor', views.show_all_actors, name='actors-main'),
    path('actor/<int:id_actor>', views.show_one_actor, name="actor-detail"),
]

feedback/models.py
from django.db import models

# Create your models here.
class FeedbackModel(models.Model):
    name = models.CharField(max_length=40)
    surname = models.CharField(max_length=40)
    feedback = models.TextField()
    rating = models.PositiveIntegerField()

    def __str__(self) -> str:
        return f"{self.name} {self.surname}"

movie_app/models.py
from locale import currency
import django
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils.text import slugify
# Create your models here.

class Director(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    director_email = models.EmailField()

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

    def get_url(self):
        return  reverse('director-detail', args=[self.id])

class DressingRoom(models.Model):
    floor = models.IntegerField()
    number = models.IntegerField(default=2)

    def __str__(self) -> str:
        return f"{self.floor} - {self.number}"

class Actor(models.Model):
    MALE = "M"
    FEMALE = "F" 
    GENDERS = [
        (MALE, 'Man'),
        (FEMALE, 'Woman'), 
    ]

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    gender = models.CharField(max_length=1, choices=GENDERS, default=MALE)
    dressing = models.OneToOneField(DressingRoom,on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self) -> str:
        if self.gender == self.MALE:
            return f'Mr {self.first_name} {self.last_name}'
        else:
            return f'Mrs {self.first_name} {self.last_name}'

    def get_url(self):
        return  reverse('actor-detail', args=[self.id])

class Movie(models.Model):
    USD = "USD"
    EUR = "EUR"
    RUB = "RUB"
    CURRENCY_CHOICES = [
        (EUR, 'Euro'),
        (USD, 'Dollars'),
        (RUB, 'Rubles'),
    ]

    name = models.CharField(max_length=40)
    rating = models.IntegerField(validators=[
                                            MinValueValidator(1),
                                            MaxValueValidator(100)
                                        ])
    year = models.IntegerField(null=True)
    budget = models.IntegerField(default=100000,validators=[
                                            MinValueValidator(1)
                                        ])
    currency_budget = models.CharField(max_length=3, choices=CURRENCY_CHOICES, default=RUB)
    slug = models.SlugField(default="", null=False)

    director = models.ForeignKey(Director, on_delete=models.PROTECT, null=True)
    actor = models.ManyToManyField(Actor)
    # def save(self, *args, **kwargs) -> None:
    #     self.slug = slugify(self.name)
    #     return super(Movie, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return f"{self.name} {self.rating}"

    def get_url(self):
        return  reverse('movie-detail', args=[self.slug])

feedback/forms.py
from cProfile import label
from dataclasses import field
from django import forms
from .models import FeedbackModel

# class FeedbackForm(forms.Form):
#     name = forms.CharField(label="Name",max_length=7,min_length=2)
#     surname = forms.CharField()
#     feedback = forms.CharField(widget=forms.Textarea(attrs={'rows':10,'cols':80}))
#     rating = forms.IntegerField(max_value=5,min_value=1)

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = FeedbackModel
        # fields = ['name','surname','feedback','rating']
        fields = '__all__'
        labels = {
            'name': "Имя"
        }
        error_messages = {
            'name' : {
                
            }
        }

feedback/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect
# Create your views here.
from django.urls import reverse
from .forms import FeedbackForm
from .models import FeedbackModel

def feedback_index(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            form.save()
            url = reverse('feedback-done')
            return HttpResponseRedirect(url)
    else:
        form = FeedbackForm()
    return render(request, 'feedback.html', context={
        "form": form
    })

def update_feedback(request, id_feedback):
    feed = get_object_or_404(FeedbackModel,id=id_feedback)
    if request.method == 'POST':
        form = FeedbackForm(request.POST, instance=feed)
        if form.is_valid():
            form.save()
            url = reverse('feedback-done')
            return HttpResponseRedirect(url)
    else:
        form = FeedbackForm(instance=feed)
    return render(request, 'feedback.html', context={
        "form": form
    })

def done(request): 

    return render(request, 'done.html')


    

movie_app/views.py
from django.shortcuts import render, get_object_or_404
from .models import Actor, Movie, Director
from django.db.models import Value
# Create your views here.


def show_all_movie(request):
    movies = Movie.objects.annotate(new_field=Value(True))
    return render(request,"all_movies.html",context={"movies":movies})

def show_all_directors(request):
    directors = Director.objects.all()
    return render(request,"all_directors.html",context={"directors":directors})

def show_all_actors(request):
    actors = Actor.objects.all()
    return render(request,"all_actors.html",context={"actors":actors})

def show_one_movie(request, slug_movie:str):
    movie = get_object_or_404(Movie, slug=slug_movie)
    context = {
        "movie": movie
        }
    return render(request,"one_movie.html",context=context)

def show_one_director(request, id_director:int):
    director = get_object_or_404(Director, id=id_director)
    context = {
        "director": director
        }
    return render(request,"one_director.html",context=context)

def show_one_actor(request, id_actor:int):
    actor = get_object_or_404(Actor, id=id_actor)
    context = {
        "actor": actor
        }
    return render(request,"one_actor.html",context=context)

templates/all_actors.html
{% extends 'base.html' %}


{% block Title %}
    Все актеры
{% endblock %}

{% block content %}
    <h2> Список всех актеров </h2>
    <ul class="info-field">
        {% for actor in actors %}
        <li> <a href="{{ actor.get_url }}">  {{ actor }} </a> </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/all_directors.html
{% extends 'base.html' %}


{% block Title %}
    Все Режиссеры
{% endblock %}

{% block content %}
    <h2> Список всех Режиссеров </h2>
    <ul class="info-field">
        {% for director in directors %}
        <li> <a href="{{ director.get_url }}">  {{ director }} </a> </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/all_movies.html
{% extends 'base.html' %}


{% block Title %}
    Все фильмы
{% endblock %}

{% block content %}
    <h2> Список всех фильмов </h2>
    <ul class="info-field">
        {% for movie in movies %}
        <li> <a href="{{ movie.get_url }}">  {{ movie }} </a> </li>
        {% endfor %}
        
    </ul>
{% endblock %}

templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> 
        {% block Title %}
            Главная
        {% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
    <nav > 
        <ul class="nav_main">
            <li class="nav-li"> <a href="{% url 'main'%}"> Main </a> </li>
            <li class="nav-li"> <a href="{% url 'actors-main'%}"> Actors </a> </li>
            <li class="nav-li"> <a href="{% url 'directors-main'%}"> Directors </a> </li>
            <li class="nav-li"> <a href="{% url 'feedback-main'%}"> Feedback </a> </li>
        </ul>
    </nav>
    <section class="about_films">
        {% block content %}
        {% endblock %}
    </section>

</body>
</html>

templates/done.html
{% extends 'base.html' %}


{% block Title %} 
{% endblock %}

{% block content %}
    <h2> Успех </h2>
{% endblock %}

templates/feedback.html
{% extends 'base.html' %}


{% block Title %} 
{% endblock %}

{% block content %}
    <h2> Оставьте отзыв</h2>
    <form action="" method="post" class="info-field">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-style {% if field.errors %} errors {% endif %}">
                {{ field.label_tag }}
                {{ field.errors }}
                {{ field }}
            </div>
        {% endfor %}
        <button type="submit"> Отправить </button>
    </form>
{% endblock %}

templates/one_actor.html
{% extends 'base.html' %}


{% block Title %}
    Информация о Актере - {{ actor.first_name }}
{% endblock %}

{% block content %}
    <h2> Информация о Актере </h2>
    <div class="info-field">
        <h3> {{ actor }} </h3>
        <h3> {{ actor.gender }} </h3>
        <hr>
        <ul>
            {% for movie in actor.movie_set.all %}
                <li> <a href="{{ movie.get_url }}">  {{ movie }} </a> </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

templates/one_director.html
{% extends 'base.html' %}


{% block Title %}
    Информация о Режиссере - {{ director.first_name }}
{% endblock %}

{% block content %}
    <h2> Информация о Режиссере </h2>
    <div class="info-field">
        <h3> {{ director }} </h3>
        <h3> {{ director.director_email }} </h3>
        <hr>
        <ul>
            {% for movie in director.movie_set.all %}
                <li> <a href="{{ movie.get_url }}">  {{ movie }} </a> </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/one_movie.html
{% extends 'base.html' %}


{% block Title %}
    Информация о фильме - {{ movie.name }}
{% endblock %}

{% block content %}
    <h2> Информация о фильме </h2>
    <div class="info-field">
        <h3> {{ movie }} </h3>
        <hr>
        <h4> Режиссер: <a href="{{ movie.director.get_url }}">  {{ movie.director }} </a> </h4>
        <hr>
        <h3> Актеры: </h3>
        <ul>
            {% for actor in movie.actor.all %} 
                <li> <a href="{{ actor.get_url }}">  {{ actor }} </a> </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}